/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StoreIndexRouteImport } from './routes/_store/index'
import { Route as StoreAboutRouteImport } from './routes/_store/about'
import { Route as StoreAccountRouteImport } from './routes/_store/account'
import { Route as StoreCheckoutRouteImport } from './routes/_store/checkout'
import { Route as StoreContactRouteImport } from './routes/_store/contact'
import { Route as StoreDiscoverRouteImport } from './routes/_store/discover'
import { Route as StoreWholesaleRouteImport } from './routes/_store/wholesale'
import { Route as StoreWishlistRouteImport } from './routes/_store/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminShippingRouteImport } from './routes/admin/shipping'
import { Route as AdminWholesaleRouteImport } from './routes/admin/wholesale'
import { Route as StoreGuidesIndexRouteImport } from './routes/_store/guides/index'
import { Route as StoreGuidesSlugRouteImport } from './routes/_store/guides/$slug'
import { Route as StoreLegalPageRouteImport } from './routes/_store/legal/$page'
import { Route as StoreOrderIdRouteImport } from './routes/_store/order.$id'
import { Route as StoreRecipesIndexRouteImport } from './routes/_store/recipes/index'
import { Route as StoreRecipesSlugRouteImport } from './routes/_store/recipes/$slug'
import { Route as StoreShopIndexRouteImport } from './routes/_store/shop/index'
import { Route as StoreShopSlugRouteImport } from './routes/_store/shop/$slug'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders.index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders.$id'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products.index'
import { Route as AdminProductsIdRouteImport } from './routes/admin/products.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAboutRoute = StoreAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAccountRoute = StoreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContactRoute = StoreContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => StoreRoute,
} as any)
const StoreDiscoverRoute = StoreDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => StoreRoute,
} as any)
const StoreWholesaleRoute = StoreWholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => StoreRoute,
} as any)
const StoreWishlistRoute = StoreWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => StoreRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWholesaleRoute = AdminWholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => AdminRoute,
} as any)
const StoreGuidesIndexRoute = StoreGuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreGuidesSlugRoute = StoreGuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreLegalPageRoute = StoreLegalPageRouteImport.update({
  id: '/legal/$page',
  path: '/legal/$page',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOrderIdRoute = StoreOrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRecipesIndexRoute = StoreRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRecipesSlugRoute = StoreRecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreShopIndexRoute = StoreShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreShopSlugRoute = StoreShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/about': typeof StoreAboutRoute
  '/account': typeof StoreAccountRoute
  '/checkout': typeof StoreCheckoutRoute
  '/contact': typeof StoreContactRoute
  '/discover': typeof StoreDiscoverRoute
  '/wholesale': typeof StoreWholesaleRoute
  '/wishlist': typeof StoreWishlistRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/wholesale': typeof AdminWholesaleRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/$slug': typeof StoreGuidesSlugRoute
  '/legal/$page': typeof StoreLegalPageRoute
  '/order/$id': typeof StoreOrderIdRoute
  '/recipes/$slug': typeof StoreRecipesSlugRoute
  '/shop/$slug': typeof StoreShopSlugRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/guides/': typeof StoreGuidesIndexRoute
  '/recipes/': typeof StoreRecipesIndexRoute
  '/shop/': typeof StoreShopIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof StoreAboutRoute
  '/account': typeof StoreAccountRoute
  '/checkout': typeof StoreCheckoutRoute
  '/contact': typeof StoreContactRoute
  '/discover': typeof StoreDiscoverRoute
  '/wholesale': typeof StoreWholesaleRoute
  '/wishlist': typeof StoreWishlistRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/wholesale': typeof AdminWholesaleRoute
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminIndexRoute
  '/guides/$slug': typeof StoreGuidesSlugRoute
  '/legal/$page': typeof StoreLegalPageRoute
  '/order/$id': typeof StoreOrderIdRoute
  '/recipes/$slug': typeof StoreRecipesSlugRoute
  '/shop/$slug': typeof StoreShopSlugRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/guides': typeof StoreGuidesIndexRoute
  '/recipes': typeof StoreRecipesIndexRoute
  '/shop': typeof StoreShopIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_store/about': typeof StoreAboutRoute
  '/_store/account': typeof StoreAccountRoute
  '/_store/checkout': typeof StoreCheckoutRoute
  '/_store/contact': typeof StoreContactRoute
  '/_store/discover': typeof StoreDiscoverRoute
  '/_store/wholesale': typeof StoreWholesaleRoute
  '/_store/wishlist': typeof StoreWishlistRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/wholesale': typeof AdminWholesaleRoute
  '/_store/': typeof StoreIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_store/guides/$slug': typeof StoreGuidesSlugRoute
  '/_store/legal/$page': typeof StoreLegalPageRoute
  '/_store/order/$id': typeof StoreOrderIdRoute
  '/_store/recipes/$slug': typeof StoreRecipesSlugRoute
  '/_store/shop/$slug': typeof StoreShopSlugRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_store/guides/': typeof StoreGuidesIndexRoute
  '/_store/recipes/': typeof StoreRecipesIndexRoute
  '/_store/shop/': typeof StoreShopIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/about'
    | '/account'
    | '/checkout'
    | '/contact'
    | '/discover'
    | '/wholesale'
    | '/wishlist'
    | '/admin/coupons'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/wholesale'
    | '/admin/'
    | '/guides/$slug'
    | '/legal/$page'
    | '/order/$id'
    | '/recipes/$slug'
    | '/shop/$slug'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/api/auth/$'
    | '/guides/'
    | '/recipes/'
    | '/shop/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/account'
    | '/checkout'
    | '/contact'
    | '/discover'
    | '/wholesale'
    | '/wishlist'
    | '/admin/coupons'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/wholesale'
    | '/'
    | '/admin'
    | '/guides/$slug'
    | '/legal/$page'
    | '/order/$id'
    | '/recipes/$slug'
    | '/shop/$slug'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/api/auth/$'
    | '/guides'
    | '/recipes'
    | '/shop'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/_store'
    | '/admin'
    | '/login'
    | '/_store/about'
    | '/_store/account'
    | '/_store/checkout'
    | '/_store/contact'
    | '/_store/discover'
    | '/_store/wholesale'
    | '/_store/wishlist'
    | '/admin/coupons'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/wholesale'
    | '/_store/'
    | '/admin/'
    | '/_store/guides/$slug'
    | '/_store/legal/$page'
    | '/_store/order/$id'
    | '/_store/recipes/$slug'
    | '/_store/shop/$slug'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/api/auth/$'
    | '/_store/guides/'
    | '/_store/recipes/'
    | '/_store/shop/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/about': {
      id: '/_store/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StoreAboutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/account': {
      id: '/_store/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof StoreAccountRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout': {
      id: '/_store/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/contact': {
      id: '/_store/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof StoreContactRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/discover': {
      id: '/_store/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof StoreDiscoverRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/wholesale': {
      id: '/_store/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof StoreWholesaleRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/wishlist': {
      id: '/_store/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof StoreWishlistRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wholesale': {
      id: '/admin/wholesale'
      path: '/wholesale'
      fullPath: '/admin/wholesale'
      preLoaderRoute: typeof AdminWholesaleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/guides/': {
      id: '/_store/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof StoreGuidesIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/guides/$slug': {
      id: '/_store/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof StoreGuidesSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/legal/$page': {
      id: '/_store/legal/$page'
      path: '/legal/$page'
      fullPath: '/legal/$page'
      preLoaderRoute: typeof StoreLegalPageRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/order/$id': {
      id: '/_store/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof StoreOrderIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/recipes/': {
      id: '/_store/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof StoreRecipesIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/recipes/$slug': {
      id: '/_store/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof StoreRecipesSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/shop/': {
      id: '/_store/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof StoreShopIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/shop/$slug': {
      id: '/_store/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof StoreShopSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StoreRouteChildren {
  StoreAboutRoute: typeof StoreAboutRoute
  StoreAccountRoute: typeof StoreAccountRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreContactRoute: typeof StoreContactRoute
  StoreDiscoverRoute: typeof StoreDiscoverRoute
  StoreWholesaleRoute: typeof StoreWholesaleRoute
  StoreWishlistRoute: typeof StoreWishlistRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreGuidesSlugRoute: typeof StoreGuidesSlugRoute
  StoreLegalPageRoute: typeof StoreLegalPageRoute
  StoreOrderIdRoute: typeof StoreOrderIdRoute
  StoreRecipesSlugRoute: typeof StoreRecipesSlugRoute
  StoreShopSlugRoute: typeof StoreShopSlugRoute
  StoreGuidesIndexRoute: typeof StoreGuidesIndexRoute
  StoreRecipesIndexRoute: typeof StoreRecipesIndexRoute
  StoreShopIndexRoute: typeof StoreShopIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAboutRoute: StoreAboutRoute,
  StoreAccountRoute: StoreAccountRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreContactRoute: StoreContactRoute,
  StoreDiscoverRoute: StoreDiscoverRoute,
  StoreWholesaleRoute: StoreWholesaleRoute,
  StoreWishlistRoute: StoreWishlistRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreGuidesSlugRoute: StoreGuidesSlugRoute,
  StoreLegalPageRoute: StoreLegalPageRoute,
  StoreOrderIdRoute: StoreOrderIdRoute,
  StoreRecipesSlugRoute: StoreRecipesSlugRoute,
  StoreShopSlugRoute: StoreShopSlugRoute,
  StoreGuidesIndexRoute: StoreGuidesIndexRoute,
  StoreRecipesIndexRoute: StoreRecipesIndexRoute,
  StoreShopIndexRoute: StoreShopIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AdminRouteChildren {
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminWholesaleRoute: typeof AdminWholesaleRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCouponsRoute: AdminCouponsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminWholesaleRoute: AdminWholesaleRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
