export type Lang = "ar" | "fr";

export const strings = {
  ar: {
    brand: "MASAALA",
    tagline: "اكتشف سحر التوابل",
    subtitle: "نكهات صُنعت لتجعل كل طبق مختلفًا.",
    discoverProducts: "اكتشف المنتجات",
    discoverBlends: "اكتشف خلطات MASAALA",
    shop: "المتجر",
    recipes: "الوصفات",
    about: "من نحن",
    contact: "اتصل بنا",
    wholesale: "للجملة والمهنيين",
    packs: "المجموعات",
    guides: "استخدمها هكذا",
    discover: "اكتشف MASAALA",
    cart: "السلة",
    wishlist: "المفضلة",
    account: "حسابي",
    login: "دخول",
    logout: "خروج",
    search: "ابحث عن توابل، خلطة، طبق…",
    searchShort: "بحث",
    addToCart: "أضف إلى السلة",
    viewProduct: "عرض المنتج",
    buyNow: "اطلب الآن",
    new: "جديد",
    bestseller: "الأكثر مبيعًا",
    sale: "عرض",
    premium: "Premium",
    weight: "الوزن",
    price: "السعر",
    stock: "المخزون",
    outOfStock: "غير متوفر",
    inStock: "متوفر",
    ingredients: "المكونات",
    howToUse: "كيف تستخدمه؟",
    storage: "الحفظ",
    origin: "بلد المنشأ",
    allergens: "الحساسية",
    nutrition: "معلومات التغذية",
    suggestedRecipes: "وصفات مقترحة",
    related: "قد يعجبك أيضاً",
    mostRequested: "الأكثر طلبًا",
    justArrived: "وصل حديثًا",
    masaalaPacks: "مجموعات MASAALA",
    algeria: "الجزائر",
    trustAlgerian: "منتجات جزائرية",
    trustCare: "اختيار بعناية",
    trustShip: "توصيل إلى مختلف الولايات",
    trustCod: "الدفع عند الاستلام",
    philosophyTitle: "نحن لا نبيع التوابل فقط",
    philosophyLead: "نحن نشتغل على النكهة.",
    philosophyBody:
      "نختار المكونات، نضبط الخلطات، ونحافظ على جودة ثابتة حتى تكون النتيجة واحدة في البيت وفي محل الجزارة. سهولة الاستخدام جزء من المنتج، وليست إضافة تسويقية.",
    pick: "اختيار المكونات",
    blend: "تطوير الخلطات",
    quality: "الجودة",
    craft: "سهولة الاستخدام",
    aboutTitle: "من نحن",
    aboutLead: "MASAALA علامة جزائرية متخصصة في التوابل والخلطات الغذائية.",
    aboutP1:
      "نعمل على منتجات عملية بنكهة واضحة، تجمع بين المطبخ الجزائري وروح الابتكار في الخلطات الجاهزة. الهدف بسيط: أن يجد الطباخ في البيت، والجزّار، وصاحب المحل، توابل يعتمد عليها.",
    aboutP2:
      "لا ندّعي وصفات سحرية ولا خصائص صحية غير مثبتة. نشتغل على المادة، على الخلطة، وعلى تجربة طلب سهلة: من الاكتشاف إلى الباب.",
    home: "الرئيسية",
    privacy: "سياسة الخصوصية",
    terms: "شروط الاستخدام",
    returns: "سياسة الاستبدال والإرجاع",
    shippingPolicy: "الشحن والتوصيل",
    checkout: "إتمام الطلب",
    guestCheckout: "الطلب بدون حساب",
    continueShop: "متابعة التسوق",
    emptyCart: "سلتك فارغة.",
    emptyCartHint: "ابدأ من المتجر أو من خلطات MASAALA.",
    qty: "الكمية",
    subtotal: "المجموع الجزئي",
    shipping: "التوصيل",
    discount: "الخصم",
    total: "الإجمالي",
    coupon: "كوبون",
    apply: "تطبيق",
    remove: "حذف",
    firstName: "الاسم",
    lastName: "اللقب",
    phone: "رقم الهاتف",
    wilaya: "الولاية",
    commune: "البلدية",
    address: "العنوان",
    notes: "ملاحظات الطلب",
    payment: "طريقة الدفع",
    cod: "الدفع عند الاستلام",
    confirmOrder: "تأكيد الطلب",
    orderOk: "تم تسجيل طلبك",
    orderThanks: "سنتواصل معك لتأكيد التوصيل.",
    orderNo: "رقم الطلب",
    minutes: "دقيقة",
    difficulty: "الصعوبة",
    easy: "سهل",
    medium: "متوسط",
    hard: "متقدم",
    servings: "حصص",
    usedProducts: "منتجات MASAALA المستخدمة",
    buyThis: "اشترِ المنتج",
    wholesaleLead: "للتجار، السوبرماركت، الجزّارين، المطاعم والموزّعين.",
    quote: "اطلب عرض أسعار للجملة",
    company: "الشركة / المحل",
    needed: "المنتجات المطلوبة",
    quantityNote: "الكمية التقريبية",
    send: "إرسال",
    sent: "وصل طلبك. سنعود إليك.",
    assistant: "مساعد MASAALA",
    cookToday: "ماذا ستطبخ اليوم؟",
    ask: "اسأل",
    chicken: "دجاج",
    meat: "لحم",
    merguez: "مرڨاز",
    grill: "شواء",
    language: "اللغة",
    filters: "التصنيف",
    all: "الكل",
    sort: "ترتيب",
    sortDefault: "الافتراضي",
    sortPriceAsc: "السعر: الأقل",
    sortPriceDesc: "السعر: الأعلى",
    noResults: "لا توجد نتائج.",
    whatsapp: "واتساب",
    follow: "تابع MASAALA",
    admin: "لوحة التحكم",
    adminHome: "الإحصائيات",
    products: "المنتجات",
    orders: "الطلبات",
    shippingRates: "أسعار التوصيل",
    coupons: "الكوبونات",
    settings: "الإعدادات",
    inquiries: "طلبات الجملة",
    save: "حفظ",
    cancel: "إلغاء",
    edit: "تعديل",
    create: "إضافة",
    delete: "حذف",
    status: "الحالة",
    stNew: "جديد",
    stConfirmed: "تم التأكيد",
    stPreparing: "قيد التحضير",
    stShipped: "تم الشحن",
    stDelivered: "تم التسليم",
    stCancelled: "ملغى",
    lowStock: "المخزون منخفض",
    sales: "المبيعات",
    aov: "متوسط قيمة الطلب",
    signInTitle: "دخول MASAALA",
    signInLead: "للطلبات السابقة والمفضلة.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    name: "الاسم",
    signIn: "دخول",
    signUp: "إنشاء حساب",
    or: "أو",
    continueGoogle: "المتابعة مع Google",
    continueX: "المتابعة مع X",
    optionalAccount: "يمكنك الطلب بدون حساب.",
    myOrders: "طلباتي",
    noOrders: "لا توجد طلبات بعد.",
    added: "أُضيف إلى السلة",
    couponOk: "تم تطبيق الكوبون",
    couponBad: "كوبون غير صالح",
    required: "مطلوب",
    phoneHint: "06 / 05 / 07",
    chooseWilaya: "اختر الولاية",
    shippingHint: "تظهر تكلفة التوصيل بعد اختيار الولاية.",
    footerBlurb: "علامة جزائرية للتوابل والخلطات. نكهة واضحة، طلب بسيط.",
    algeriaFlag: "منتجات جزائرية",
    heroKicker: "علامة توابل جزائرية",
    seeAll: "عرض الكل",
    useThis: "استخدم",
    packIncludes: "تتضمن المجموعة",
    minStock: "حد التنبيه",
    sku: "المرجع",
    active: "نشط",
    imageUrl: "رابط الصورة",
    categories: "التصنيفات",
    customer: "العميل",
    date: "التاريخ",
    period: "الفترة",
    byWilaya: "المبيعات حسب الولاية",
    topProducts: "الأكثر مبيعًا",
    newOrders: "طلبات جديدة",
    delivered: "مسلّمة",
    cancelled: "ملغاة",
    orderCount: "عدد الطلبات",
    notAdmin: "هذا الحساب ليس حساب إدارة.",
    firstAdmin: "أنت أول من يدخل: أصبحت مدير المتجر.",
    close: "إغلاق",
    menu: "القائمة",
    resultsFor: "نتائج",
    freeAbove: "التوصيل يُحسب حسب الولاية",
    stepDiscover: "اكتشف",
    stepKnow: "تعرّف",
    stepChoose: "اختر",
    stepCart: "أضف للسلة",
    stepOrder: "اطلب",
    legalUpdated: "آخر تحديث: سبتمبر 2026",
    brandLogo: "الشعار (Logo)",
    brandLogoHint: "ارفع صورة الشعار من هاتفك أو حاسوبك. تظهر في أعلى وأسفل المتجر.",
    hideLogoText: "الشعار فيه الاسم — لا تُظهر كلمة MASAALA بجانبه",
    socialHint: "الصق رابط صفحتك. الزبون يضغط عليه من أسفل المتجر ومن أيقونات التواصل.",
    instagramLabel: "رابط إنستغرام",
    facebookLabel: "رابط فيسبوك",
    tiktokLabel: "رابط تيك توك",
    shopUrlLabel: "رابط المتجر — للزبائن",
    adminUrlLabel: "رابط الإدارة — لك وحدك",
    shopUrlHint: "انشر هذا على فيسبوك وإنستغرام وواتساب. الزبون يرى المنتجات ويطلب.",
    adminUrlHint: "لا تنشر هذا الرابط. الزبون الذي يفتحه لا يستطيع تعديل المتجر.",
    copyLink: "نسخ الرابط",
    copied: "تم النسخ",
    openShop: "فتح المتجر",
    adminLoginTitle: "دخول الإدارة",
    adminLoginLead: "هذه الصفحة خاصة بصاحب المتجر. الزبون يدخل من رابط المتجر فقط.",
    phoneLabel: "رقم الهاتف",
    whatsappHint: "رقم دولي بدون + مثل 213770000000 — يظهر زر واتساب للزبون",
    contactSection: "الهاتف وواتساب",
    brandSection: "الشعار والهوية",
    socialSection: "روابط التواصل الاجتماعي",
    saved: "تم الحفظ",
    doNow: "ماذا تفعل الآن",
    step1Title: "١. انسخ رابط الزبائن",
    step1Body: "هذا الرابط الأخضر هو الذي تنشره على فيسبوك. لا تنشر رابط الإدارة.",
    step2Title: "٢. الشعار والتواصل",
    step2Body: "ارفع الشعار، وأضف الهاتف وواتساب وروابط إنستغرام وفيسبوك وتيك توك.",
    step3Title: "٣. أضف منتجاتك",
    step3Body: "الصورة، الاسم، السعر، الوزن، والمخزون. تظهر مباشرة في المتجر.",
    step4Title: "٤. راجع المتجر",
    step4Body: "افتح المتجر كما يراه الزبون وتأكد أن كل شيء صحيح.",
    goSettings: "فتح الإعدادات",
    goProducts: "إضافة منتج",
    moreDetails: "تفاصيل إضافية (اختياري)",
    photoHint: "اضغط لرفع صورة المنتج من هاتفك",
    essentials: "المعلومات الأساسية",
    confirmCod: "الدفع عند الاستلام",
  },
  fr: {
    brand: "MASAALA",
    tagline: "Découvrez la magie des épices",
    subtitle: "Des saveurs pensées pour changer chaque plat.",
    discoverProducts: "Voir les produits",
    discoverBlends: "Voir les mélanges MASAALA",
    shop: "Boutique",
    recipes: "Recettes",
    about: "À propos",
    contact: "Contact",
    wholesale: "Gros & professionnels",
    packs: "Packs",
    guides: "Utilisez-les ainsi",
    discover: "Découvrir MASAALA",
    cart: "Panier",
    wishlist: "Favoris",
    account: "Compte",
    login: "Connexion",
    logout: "Déconnexion",
    search: "Épice, mélange, plat…",
    searchShort: "Recherche",
    addToCart: "Ajouter au panier",
    viewProduct: "Voir le produit",
    buyNow: "Commander",
    new: "Nouveau",
    bestseller: "Meilleure vente",
    sale: "Offre",
    premium: "Premium",
    weight: "Poids",
    price: "Prix",
    stock: "Stock",
    outOfStock: "Rupture",
    inStock: "En stock",
    ingredients: "Ingrédients",
    howToUse: "Comment l'utiliser ?",
    storage: "Conservation",
    origin: "Origine",
    allergens: "Allergènes",
    nutrition: "Nutrition",
    suggestedRecipes: "Recettes associées",
    related: "Vous aimerez aussi",
    mostRequested: "Les plus demandés",
    justArrived: "Nouveautés",
    masaalaPacks: "Packs MASAALA",
    algeria: "Algérie",
    trustAlgerian: "Produits algériens",
    trustCare: "Sélection soignée",
    trustShip: "Livraison dans les wilayas",
    trustCod: "Paiement à la livraison",
    philosophyTitle: "Nous ne vendons pas seulement des épices",
    philosophyLead: "Nous travaillons le goût.",
    philosophyBody:
      "Choix de la matière, mise au point des mélanges, qualité stable — à la maison comme en boucherie. La facilité d'usage fait partie du produit.",
    pick: "Choix des ingrédients",
    blend: "Création des mélanges",
    quality: "Qualité",
    craft: "Facilité d'usage",
    aboutTitle: "À propos",
    aboutLead: "MASAALA est une marque algérienne d'épices et de mélanges.",
    aboutP1:
      "Nous faisons des produits utiles, au goût net, entre cuisine algérienne et mélanges contemporains. Le cuisinier à la maison, le boucher et le commerçant doivent pouvoir s'y fier.",
    aboutP2:
      "Pas d'allégations de santé, pas de slogans vides. La matière, le mélange, et une commande simple : de la découverte jusqu'à la porte.",
    home: "Accueil",
    privacy: "Confidentialité",
    terms: "Conditions",
    returns: "Retours",
    shippingPolicy: "Livraison",
    checkout: "Commander",
    guestCheckout: "Commander sans compte",
    continueShop: "Continuer vos achats",
    emptyCart: "Votre panier est vide.",
    emptyCartHint: "Commencez par la boutique ou les mélanges.",
    qty: "Qté",
    subtotal: "Sous-total",
    shipping: "Livraison",
    discount: "Remise",
    total: "Total",
    coupon: "Coupon",
    apply: "Appliquer",
    remove: "Retirer",
    firstName: "Prénom",
    lastName: "Nom",
    phone: "Téléphone",
    wilaya: "Wilaya",
    commune: "Commune",
    address: "Adresse",
    notes: "Notes",
    payment: "Paiement",
    cod: "Paiement à la livraison",
    confirmOrder: "Confirmer la commande",
    orderOk: "Commande enregistrée",
    orderThanks: "Nous vous contactons pour confirmer la livraison.",
    orderNo: "N° de commande",
    minutes: "min",
    difficulty: "Difficulté",
    easy: "Facile",
    medium: "Moyen",
    hard: "Avancé",
    servings: "parts",
    usedProducts: "Produits MASAALA utilisés",
    buyThis: "Acheter le produit",
    wholesaleLead: "Commerçants, supermarchés, bouchers, restaurants, distributeurs.",
    quote: "Demander un tarif gros",
    company: "Société / magasin",
    needed: "Produits souhaités",
    quantityNote: "Volume approximatif",
    send: "Envoyer",
    sent: "Demande reçue. Nous revenons vers vous.",
    assistant: "Assistant MASAALA",
    cookToday: "Que cuisinez-vous aujourd'hui ?",
    ask: "Demander",
    chicken: "Poulet",
    meat: "Viande",
    merguez: "Merguez",
    grill: "Grillade",
    language: "Langue",
    filters: "Catégorie",
    all: "Tous",
    sort: "Tri",
    sortDefault: "Défaut",
    sortPriceAsc: "Prix croissant",
    sortPriceDesc: "Prix décroissant",
    noResults: "Aucun résultat.",
    whatsapp: "WhatsApp",
    follow: "Suivre MASAALA",
    admin: "Administration",
    adminHome: "Tableau de bord",
    products: "Produits",
    orders: "Commandes",
    shippingRates: "Tarifs livraison",
    coupons: "Coupons",
    settings: "Réglages",
    inquiries: "Demandes gros",
    save: "Enregistrer",
    cancel: "Annuler",
    edit: "Modifier",
    create: "Ajouter",
    delete: "Supprimer",
    status: "Statut",
    stNew: "Nouveau",
    stConfirmed: "Confirmé",
    stPreparing: "Préparation",
    stShipped: "Expédié",
    stDelivered: "Livré",
    stCancelled: "Annulé",
    lowStock: "Stock bas",
    sales: "Ventes",
    aov: "Panier moyen",
    signInTitle: "Connexion MASAALA",
    signInLead: "Commandes, favoris et administration.",
    email: "E-mail",
    password: "Mot de passe",
    name: "Nom",
    signIn: "Connexion",
    signUp: "Créer un compte",
    or: "ou",
    continueGoogle: "Continuer avec Google",
    continueX: "Continuer avec X",
    optionalAccount: "Vous pouvez commander sans compte.",
    myOrders: "Mes commandes",
    noOrders: "Pas encore de commande.",
    added: "Ajouté au panier",
    couponOk: "Coupon appliqué",
    couponBad: "Coupon invalide",
    required: "Requis",
    phoneHint: "06 / 05 / 07",
    chooseWilaya: "Choisir la wilaya",
    shippingHint: "Les frais s'affichent après le choix de la wilaya.",
    footerBlurb: "Marque algérienne d'épices et de mélanges. Goût net, commande simple.",
    algeriaFlag: "Produits algériens",
    heroKicker: "Maison d'épices algérienne",
    seeAll: "Tout voir",
    useThis: "Utiliser",
    packIncludes: "Le pack contient",
    minStock: "Seuil d'alerte",
    sku: "SKU",
    active: "Actif",
    imageUrl: "URL image",
    categories: "Catégories",
    customer: "Client",
    date: "Date",
    period: "Période",
    byWilaya: "Ventes par wilaya",
    topProducts: "Meilleures ventes",
    newOrders: "Nouvelles commandes",
    delivered: "Livrées",
    cancelled: "Annulées",
    orderCount: "Commandes",
    notAdmin: "Ce compte n'est pas administrateur.",
    firstAdmin: "Premier accès : vous devenez administrateur.",
    close: "Fermer",
    menu: "Menu",
    resultsFor: "Résultats",
    freeAbove: "Livraison selon la wilaya",
    stepDiscover: "Découvrir",
    stepKnow: "Comprendre",
    stepChoose: "Choisir",
    stepCart: "Panier",
    stepOrder: "Commander",
    legalUpdated: "Mise à jour : septembre 2026",
    brandLogo: "Logo",
    brandLogoHint: "Téléversez le logo. Il s'affiche en haut et en bas de la boutique.",
    hideLogoText: "Le logo contient le nom — ne pas afficher MASAALA à côté",
    socialHint: "Collez l'URL de vos pages. Le client y accède depuis le pied de page.",
    instagramLabel: "Lien Instagram",
    facebookLabel: "Lien Facebook",
    tiktokLabel: "Lien TikTok",
    shopUrlLabel: "Lien boutique — clients",
    adminUrlLabel: "Lien admin — vous seul",
    shopUrlHint: "Publiez ce lien sur Facebook, Instagram et WhatsApp.",
    adminUrlHint: "Ne publiez pas ce lien. Un client ne peut pas modifier la boutique.",
    copyLink: "Copier le lien",
    copied: "Copié",
    openShop: "Ouvrir la boutique",
    adminLoginTitle: "Connexion administration",
    adminLoginLead: "Page réservée au gérant. Les clients utilisent le lien boutique.",
    phoneLabel: "Téléphone",
    whatsappHint: "Numéro international sans + (ex. 213770000000)",
    contactSection: "Téléphone et WhatsApp",
    brandSection: "Logo et identité",
    socialSection: "Réseaux sociaux",
    saved: "Enregistré",
    doNow: "Que faire maintenant",
    step1Title: "1. Copier le lien client",
    step1Body: "Publiez le lien vert sur Facebook. Ne publiez pas le lien admin.",
    step2Title: "2. Logo et contact",
    step2Body: "Logo, téléphone, WhatsApp, Instagram, Facebook, TikTok.",
    step3Title: "3. Ajouter vos produits",
    step3Body: "Photo, nom, prix, poids et stock. Visible tout de suite.",
    step4Title: "4. Voir la boutique",
    step4Body: "Ouvrez la boutique comme un client et vérifiez.",
    goSettings: "Ouvrir les réglages",
    goProducts: "Ajouter un produit",
    moreDetails: "Détails supplémentaires (optionnel)",
    photoHint: "Appuyez pour téléverser une photo",
    essentials: "Informations essentielles",
    confirmCod: "Paiement à la livraison",
  },
} as const;

export type MessageKey = keyof typeof strings.ar;
