export type Wilaya = {
  code: string;
  ar: string;
  fr: string;
  shipping: number;
};

export const WILAYAS: Wilaya[] = [
  { code: "01", ar: "أدرار", fr: "Adrar", shipping: 900 },
  { code: "02", ar: "الشلف", fr: "Chlef", shipping: 600 },
  { code: "03", ar: "الأغواط", fr: "Laghouat", shipping: 750 },
  { code: "04", ar: "أم البواقي", fr: "Oum El Bouaghi", shipping: 650 },
  { code: "05", ar: "باتنة", fr: "Batna", shipping: 600 },
  { code: "06", ar: "بجاية", fr: "Béjaïa", shipping: 550 },
  { code: "07", ar: "بسكرة", fr: "Biskra", shipping: 700 },
  { code: "08", ar: "بشار", fr: "Béchar", shipping: 900 },
  { code: "09", ar: "البليدة", fr: "Blida", shipping: 450 },
  { code: "10", ar: "البويرة", fr: "Bouira", shipping: 500 },
  { code: "11", ar: "تمنراست", fr: "Tamanrasset", shipping: 1200 },
  { code: "12", ar: "تبسة", fr: "Tébessa", shipping: 700 },
  { code: "13", ar: "تلمسان", fr: "Tlemcen", shipping: 650 },
  { code: "14", ar: "تيارت", fr: "Tiaret", shipping: 600 },
  { code: "15", ar: "تيزي وزو", fr: "Tizi Ouzou", shipping: 500 },
  { code: "16", ar: "الجزائر", fr: "Alger", shipping: 400 },
  { code: "17", ar: "الجلفة", fr: "Djelfa", shipping: 700 },
  { code: "18", ar: "جيجل", fr: "Jijel", shipping: 550 },
  { code: "19", ar: "سطيف", fr: "Sétif", shipping: 550 },
  { code: "20", ar: "سعيدة", fr: "Saïda", shipping: 650 },
  { code: "21", ar: "سكيكدة", fr: "Skikda", shipping: 550 },
  { code: "22", ar: "سيدي بلعباس", fr: "Sidi Bel Abbès", shipping: 600 },
  { code: "23", ar: "عنابة", fr: "Annaba", shipping: 550 },
  { code: "24", ar: "قالمة", fr: "Guelma", shipping: 600 },
  { code: "25", ar: "قسنطينة", fr: "Constantine", shipping: 550 },
  { code: "26", ar: "المدية", fr: "Médéa", shipping: 500 },
  { code: "27", ar: "مستغانم", fr: "Mostaganem", shipping: 600 },
  { code: "28", ar: "المسيلة", fr: "M'Sila", shipping: 650 },
  { code: "29", ar: "معسكر", fr: "Mascara", shipping: 600 },
  { code: "30", ar: "ورقلة", fr: "Ouargla", shipping: 850 },
  { code: "31", ar: "وهران", fr: "Oran", shipping: 500 },
  { code: "32", ar: "البيض", fr: "El Bayadh", shipping: 800 },
  { code: "33", ar: "إليزي", fr: "Illizi", shipping: 1200 },
  { code: "34", ar: "برج بوعريريج", fr: "Bordj Bou Arreridj", shipping: 550 },
  { code: "35", ar: "بومرداس", fr: "Boumerdès", shipping: 450 },
  { code: "36", ar: "الطارف", fr: "El Tarf", shipping: 600 },
  { code: "37", ar: "تندوف", fr: "Tindouf", shipping: 1200 },
  { code: "38", ar: "تيسمسيلت", fr: "Tissemsilt", shipping: 600 },
  { code: "39", ar: "الوادي", fr: "El Oued", shipping: 800 },
  { code: "40", ar: "خنشلة", fr: "Khenchela", shipping: 650 },
  { code: "41", ar: "سوق أهراس", fr: "Souk Ahras", shipping: 650 },
  { code: "42", ar: "تيبازة", fr: "Tipaza", shipping: 450 },
  { code: "43", ar: "ميلة", fr: "Mila", shipping: 600 },
  { code: "44", ar: "عين الدفلى", fr: "Aïn Defla", shipping: 500 },
  { code: "45", ar: "النعامة", fr: "Naâma", shipping: 850 },
  { code: "46", ar: "عين تموشنت", fr: "Aïn Témouchent", shipping: 600 },
  { code: "47", ar: "غرداية", fr: "Ghardaïa", shipping: 800 },
  { code: "48", ar: "غليزان", fr: "Relizane", shipping: 600 },
  { code: "49", ar: "تيميمون", fr: "Timimoun", shipping: 1000 },
  { code: "50", ar: "برج باجي مختار", fr: "Bordj Badji Mokhtar", shipping: 1400 },
  { code: "51", ar: "أولاد جلال", fr: "Ouled Djellal", shipping: 750 },
  { code: "52", ar: "بني عباس", fr: "Béni Abbès", shipping: 1000 },
  { code: "53", ar: "عين صالح", fr: "In Salah", shipping: 1200 },
  { code: "54", ar: "عين قزام", fr: "In Guezzam", shipping: 1400 },
  { code: "55", ar: "تقرت", fr: "Touggourt", shipping: 850 },
  { code: "56", ar: "جانت", fr: "Djanet", shipping: 1300 },
  { code: "57", ar: "المغير", fr: "El M'Ghair", shipping: 850 },
  { code: "58", ar: "المنيعة", fr: "El Meniaa", shipping: 900 },
];
